export const TAGS_CONFIG = [
	{ id: 1, name: 'UI Design', color: 'red' },
	{ id: 2, name: 'Dashboard', color: 'blue' },
	{ id: 3, name: 'Feature', color: 'violet' },
	{ id: 4, name: 'Search', color: 'yellow' },
	{ id: 5, name: 'Test', color: 'red' },
	{ id: 6, name: 'UX', color: 'blue' },
	{ id: 7, name: 'Navigation', color: 'violet' },
	{ id: 8, name: 'Frontend', color: 'yellow' },
	{ id: 9, name: 'Route', color: 'red' },
	{ id: 10, name: 'Bug', color: 'blue' },
	{ id: 11, name: 'Authentication', color: 'violet' },
	{ id: 12, name: 'Backend', color: 'yellow' },
	{ id: 13, name: 'Activity', color: 'red' },
	{ id: 14, name: 'Feed', color: 'blue' },
	{ id: 15, name: 'feedback', color: 'violet' },
	{ id: 16, name: 'form', color: 'yellow' },
	{ id: 17, name: 'UI', color: 'red' },
]
